### ISSUE TITLE
Error converting: Unable to convert aaxc file, missing audible_key/audible_iv pair

### ISSUE THREAD

**Issue by rjmellor** [openaudible/openaudible#1003]
How do I resolve this issue with three audible book titles that will not convert to m4b?

**Comment by openaudible** [comment]
They won't be able to be converted, so the AAX file should be deleted.. usually this is because you downloaded them without the OpenAudible application (maybe copied from an android device?) You can delete the book from OpenAudible using the Action Menu.

So use the OpenAudible app to connect to your library, then download and convert using the application.

**Comment by rjmellor** [comment]
Deleting the title, closing the program and downloading the title again, worked.
