### ISSUE TITLE
Anomalie pour Extraire les chapitres d'un livre audio

### ISSUE THREAD

**Issue by JONtropFORT** [openaudible/openaudible#1045]
Description of problem 
Bonjour, en souhaitant extraire les chappitres d'un livre audio, j'ai le message d'erreur suivant :

 Error 7 nouvelles de Lovercraft Cannot Run Program 
\\ffprobe.exe : CreateProcess error=216 , Cette version de %1 n'est pas compatible avec la version de windows actuellement exécutée. Vérifiez dans les informations systemes de votre ordinateur, puis contactez l'éditeur du logiciel.

Pourriez vous m'aider ?

Merci par avance.

**Comment by openaudible** [comment]
You may be using Windows N. Which doesn’t include some of the required dlls for ffmpeg.

Please google and install that “mfplat.dll” or install the whole media platform:

https://support.microsoft.com/en-us/topic/media-feature-pack-for-n-editions-of-windows-10-version-1607-b657cb70-33e7-1f11-7119-3b4b50be4e89

**Comment by openaudible** [comment]
After looking at your error report, we think the most likely problem is that you have a virus that can be removed:

https://support.microsoft.com/en-gb/topic/error-message-runtime-error-216-1d0db575-c9bf-94e9-c432-2315c5bab9d5

There is also a chance it is due to a very old system or not enough RAM.. but try the above link first.

I hope that helps.
