### ISSUE TITLE
unable to connect to Audible

### ISSUE THREAD

**Issue by rithub19** [openaudible/openaudible#1105]
Hi, I just installed OpenAudible, and tried to connect to Audible from Controls>Connect to Audible. I typed my sign in information in the authentication window, but it keeps saying that my userID or password is incorrect. I checked my region, it's US, I updated my password and am able to log in Audible using the new sign in. What am I doing wrong? I appreciate your help.

**Comment by openaudible** [comment]
It should work... If your audible user name is not an email, make sure to check the legacy login box. Otherwise, make sure it isn't checked. 
It is possible to lose track of passwords since most browsers auto-fill your user/pass.. so double check you're entering the same into a new browser and the OA browser.

**Comment by rithub19** [comment]
Thank you! I had the legacy login box checked using my email address. I unchecked it and now I was able to log in. Thank you so much!
