### ISSUE TITLE
Invalid hash is not AAX

### ISSUE THREAD

**Issue by Cnag1** [openaudible/openaudible#1108]
I have no idea what this means.  But I've spent hours trying to download some children's books I've purchased for my kids.  They were not freebies.  I have converted others that I got at the same time, but ther are 11 that won't work.  

SECOND, I have many other books on Audible that I've purchased but won't download to openaudible.  I have logged out and logged back in they still won't download.  Please help.  I'm a busy mom and just want to convery to mp3 for my kids' Yoto players!

**Comment by openaudible** [comment]
This should be fixed in the latest beta.
https://openaudible.org/beta 

For downloading, you need to make sure you're logged into your account and you've done a recent "full library scan". You should also make sure the book is still available in your audible library. Sometimes books become unavailable.. so you may need to re-add the book.

**Comment by openaudible** [comment]
Try 3.7 and reply here or email us a bug report if still having problems. Closing since there is a new release that should have better address this or at least provide a better error message.
