### ISSUE TITLE
Feature Request: Customize Book List Export Fields

### ISSUE THREAD

**Issue by Vlahn** [openaudible/openaudible#1109]
Hi,

I would like to be able to customise the book list export feature. I use the .csv export frequently with Open Audible.

Specifically:
- Select which fields to include and not include in the exported book list
- Select the order in which the selected fields should be displayed
- Customise the Title of Fields (Ave. Rating becomes Average Rating etc)
- Change the date formatting to be ISO (2023-01-16 etc) which is better for sorting by
- Limit the display of Rating Data to 2 decimal places (8.05698 is data overkill)

Having a way to customise whatever template OpenAudible is using would be super helpful. Even if its an option 'outside' of the app. If you can point me to a settings file or something similar which can be modified and not over-written when the app updates itself.

Thanks.

**Comment by openaudible** [comment]
I would try to use the books.json as a data source and have it updated automatically when the file changes. That way you can create the headers and format the data any way you like. 

You may need to google how to use a json data source with your version of Excel. CSV is not a great option since it only updates when you manually do an export. 

However we will change the date and rating output. 

Let us know how it works!
