### ISSUE TITLE
Optional fields on Web Page generation

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1121]
It would be very useful to include series_name and series_sequence as sortable headers in the two full page lists generated by the app (one with images and the other without images).  Filtering and sorting by series is very useful when dealing with large Audiobook libraries.  

I have implemented this by minor changes in index.html and in assets/openAudible.js, but these are overwritten each time books are added to my library and the web page is regenerated. I can of course just re-overwrite the generated code with my two modules, a messy solution and I cannot figure out how to do it properly.

Is there any chance of a future change that would allow users to specify which column(s) are used in the generated web pages?

**Comment by openaudible** [comment]
We are working on scrapping a lot of the web page logic.. so that it doesn't make a full copy... But it is in progress.
The logic used to be if the file was already there, we wouldn't upgrade it, but then it became difficult to make an upgrade to the app that would update the changed html.

How about if we find a file called web_updated.sh or web_updated.bat in the OA prefs directory, we can run it after the web pages build and you can copy whatever html files you need using that..  That would take 5 minutes to add.

**Comment by oboe45** [comment]
Yes, that will work for me.   I have a good interim solution that survives
a rebuild after adding books at Audible.  If I could only figure out how to
concatenate the Series name with a *two* digit sequence nuimber instead of
the 1-2 digits in the generated Jason book file, then it would be perfect.

I must say the product is currently really stable and reliable and does
just about everything I need to access and play the books. Thanks for the
product.

**Comment by openaudible** [comment]
Added to latest beta... https://openaudible.org/beta

Untested! 

javascript might help with the two digit padding.. but no idea! 

Thanks for the kind comments.. Appreciate them!
