### ISSUE TITLE
MP3's not importing

### ISSUE THREAD

**Issue by digitalsea1** [openaudible/openaudible#1152]
Hi, I purchased openaudible so that I could also import MP3/M3A books and listen to them on the Audible app. When I choose 'import book' and select the file. It flashes up on my screen that's it's importing for a split second (see screenshot), but then the important audio book is nowhere to be found within openaudible.

Is this a bug or can I not import mp3/m4a files?

![CleanShot 2023-03-03 at 16 36 37](https://user-images.githubusercontent.com/88224090/222776170-81d1e686-6b12-40c3-81d5-6b7e8b1c2a15.png)

**Comment by openaudible** [comment]
You'll have to look at the console window and look at the error that is generated. 
File menu: Console.
The book may need to be playable... but otherwise I can't think of why it wouldn't be added to OpenAudible.
That all said, you can not upload arbitrary files to Audible... OpenAudible only downloads your audible content to make a backup.

**Comment by digitalsea1** [comment]
Ok thanks
