### ISSUE TITLE
Converting to MP3, error missing key

### ISSUE THREAD

**Issue by smctlc622** [openaudible/openaudible#1157]
I just did a full sync to my audible account. There are three files that won't convert. The error says "Error converting: Unable to convert aaxc file, missing audible_key/audible_iv pair"

**Comment by openaudible** [comment]
Usually that is due to being downloaded from android or another app. 
Upgrade to the latest version. Some issues have been addressed in later versions of OpenAudible.
You may need to Action:Delete Book and do a Controls: Full Audible Library Sync, download and convert.
We did release 3.7 which has a number of improvements for automatically re-downloading a book missing keys.
