### ISSUE TITLE
REQUEST Language of Audiobook

### ISSUE THREAD

**Issue by christianmerges** [openaudible/openaudible#1229]
It would be great to see the Language of the Audiobook in the Table and Book Details. Also it would be great to save the books by language in different folders.

**Comment by openaudible** [comment]
We can add the language as an optional table item.

**Comment by christianmerges** [comment]
That would be already a great solution, because than we can sort by language, split selected books, move the folders into a subfolder and then move on with the next language. When can i expect the implementation 😬

**Comment by christianmerges** [comment]
Please also get the type of media from audible. For german Audible Account, possible options are:
gekürztes Hörbuch
Hörspiel
Originalaufnahme Hörbuch
Rede
Sprachkurs
Ungekürztes Hörbuch
Vortrag

**Comment by openaudible** [comment]
Ok. I added language to the book table option in the beta. 
openaudible.org/beta
 Only accessible by right clicking in the table and selecting book table options menu.

**Comment by openaudible** [comment]
The "format_type" contains abridged or unabridged... but can also contain other values like original recording. So that sounds like the field you want. We currently only capture whether something is abridged or not. 
Currently we don't make a copy of that info, but will start to monitor that field. Marking as feature request.

**Comment by christianmerges** [comment]
I can confirm the language table item working. Thanks for implementing.
