### ISSUE TITLE
Convert to M4b

### ISSUE THREAD

**Issue by letternews** [openaudible/openaudible#1284]
When having only m4a there is no option to convert to m4b only mp3.
Thanks

**Comment by letternews** [comment]
One more thing. Why does convert to m4b on a mp3 file with 64kpbs convert to a file with 128 kpbs m4b?

**Comment by openaudible** [comment]
Oh, good catch. Just rename the m4a to m4b. They are essentially the same file.  But we didn't check for that possibility. (Although we have a migrate library feature in the Manage Libraries that is supposed to rename m4a to m4b.)

For mp3->m4b, we just let ffmpeg decide the rate. It is usually pretty good. But we didn't really plan for the mp3 to m4b-- it was a feature request and its generally not a great idea since you're going from a lossy format to a more lossy format. But some people requested it.

**Comment by letternews** [comment]
would it be a big hassle to implement a prespecified conversion preference? I guess I'm not the only user who would benefit. Thanks
