### ISSUE TITLE
Unable to submit bug through Openaudible app

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1307]
when trying to submit a bug through about -> submit bug report
it says issue number required

i am using 3.9.7 on windows 11 64bit

**Comment by openaudible** [comment]
I tested it. Try again using issue 1307. Send any error. Omit any personal data. Just the error.

**Comment by feldegast** [comment]
it says thank you for submitting but when i use 1307 as my error number it doesn't add anything here

**Comment by feldegast** [comment]
it looks like it doesn't get the next available issue number to report a new bug to github....

**Comment by feldegast** [comment]
the time openaudible said thank you for submitting (mentioned above), there is no record of that submission either in the github issues for this project as well as it not showing in my list of activity in my github account, it looks like it gets submitted to nowhere.....

**Comment by openaudible** [comment]
Ah- we get your bug report but it goes to our backend server. We don’t automatically post anything here. 

Your first bug report says: this dialogue wasn't shown when i tried with the earlier version of openaudible

but that isn’t clear what the problem is. You can only submit a bug if you’re using the latest version(s).

**Comment by feldegast** [comment]
it was the current version at the time......at least i think it was
