### ISSUE TITLE
I'm having issues with aax names/title mismatch.  And a lot of *.1.aax files. 

### ISSUE THREAD

**Issue by Meesh73** [openaudible/openaudible#1319]
Issue #1 - files are not being named from the titles
Issue #2 - filenames are getting '.1.aax' appended when unnecessary. 
Issue #3 - shit gets weird between a colon and a dash in the title for m4b files

![Naming](https://github.com/openaudible/openaudible/assets/62067408/d3b49c09-2470-4933-897e-2e0d3a47ec18)

On the naming.png file you'll see that Dragonslayer.1.aax shouldn't be named this way.  It's the only book with the name, so .1. should not be needed.  

Similar issue with the Elantris books; I have two similar files that should be pulling their names from the title but don't.  If they did, the .1. wouldn't be there and it would be clear that one is the anniversary edition. 

I have tons of books that were re-downloaded into my library because of a ':' rather than a '-' in the title.  It isn't obvious which one should be kept (I believe it's the colon) because they both have the same date.  I have check the metadata to make a determination. 

In Abaddons_Gate.png I'll keep the larger one and do another sync and see if I chose wisely. 

![Abaddons_Gate](https://github.com/openaudible/openaudible/assets/62067408/b4687a57-701a-4ccf-b969-ad46f180e1a3)

![Dash_colon](https://github.com/openaudible/openaudible/assets/62067408/bf0dae7e-44da-4878-94c3-cf6ba706ae1d)

**Comment by openaudible** [comment]
That is a lot to digest. A few things about duplicates. 

You can and should delete duplicates when they occur. You can find possible duplicates by selecting "Possible Duplicates" in the Find drop-down combo box. 

You can select any two books in the OpenAudible books table and those two books will be compared. 

We typically don't use colons in the file names because they cause problems with Windows-- but that isn't to say they aren't allowed.

Using OpenAudible to download and convert the AAX files is the best strategy. If you have downloaded them previously and import them, you may lose out on some meta data or file naming strategy.

Generally, OpenAudible will refuse to import two books with the same ASIN and/or Product ID. So if you have duplicates, you'll want to look at those two key values.

**Comment by Meesh73** [comment]
Sorry I dumped so much in one post on ya.  
Thanks for the reply and I've gone through and removed the duplicates, checking each to ensure I have the most current - I hope.  I'll do another sync and see if the issue comes back up again.  

Thanks again!
