### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by christian-thiele** [openaudible/openaudible#1368]
Are there any plans for command line support?
My goal is to automate the process of making audible audiobooks available to my jellyfin server.

OpenAudible scan / download could be triggered once a day by a cron job for example.

**Comment by openaudible** [comment]
Not super easy to do unless we added a rest server. Uh... hoping to avoid that. You can set the automate buttons and just quit and restart the app to automatically refresh, download and convert on startup. Cron isn't a great option, since if you buy a book, that's when you want to trigger the update, not wait til the next interval. 
Marking as feature request but don't hold your breath... a server would be "fun" but not fun.
