### ISSUE TITLE
Error Downloading: ASIN[xxxxxxxxxx] is not eligble for AYCL

### ISSUE THREAD

**Issue by KSov3** [openaudible/openaudible#1385]
Error downloading: Asin: [xxxxxxxxxx] is not eligible for AYCL.

I receive this error one every book I try to download. The ASIN number changes, and corresponds to the correct book in audible when I search that on google.  Both audible accounts I use show up as registered with an OK symbol, the libraries refresh correctly and I can see my most recent books.

**Comment by openaudible** [comment]
Usually that just means the book is no longer "free with membership". Check that it is in your library and still accessible in the Audible app.

If you're using multiple accounts, that might be a bug in 4.1.1. A similar issue has been fixed in the beta, which you're welcome to try: https://openaudible.org/beta
