### ISSUE TITLE
CLI Compatiblity

### ISSUE THREAD

**Issue by macskay** [openaudible/openaudible#139]
This is more of a feature request rather than an actual bug. Are there any plans to support a command-line compatibility for downloading and converting the library?

**Comment by openaudible** [comment]
It gets difficult, because audible.com uses several techniques to block automated logging in, such as captchas. That was the original goal, but ended up using the built-in browser to let the user log in--that way I don't attempt to save or use usernames and passwords. So no plans. Lots of work and no reward. 

However, all of the conversion code is command lines and are output in the console window if you want to see how it is done. However, a lot goes on behind the scenes, so it isn't trivial.
