### ISSUE TITLE
Missing Author link

### ISSUE THREAD

**Issue by CrustyApplesniffer** [openaudible/openaudible#145]
I've clean all my previously downloaded audio-books and refreshed the info (Action/Refresh info).
All Authors links have been removed.
![image](https://user-images.githubusercontent.com/37656975/58506039-aaa83400-818e-11e9-9538-a76a132a8cc7.png)

Moreover, clicking on the narrator link open the classic landing page, not the one with the result of all audio-books read by this narrator
![image](https://user-images.githubusercontent.com/37656975/58506284-36ba5b80-818f-11e9-8d5a-41df795c4272.png)

**Comment by openaudible** [comment]
Post a link to a book URL (you can delete anything after the ? in the URL) and I can test parsing that book page to make sure it gets the author. It may be a .fr problem.

Also, your language should have been detected as "fr" and the app should be showing French language. Did you set your locale for French? Not sure why the java VM didn't recognize your locale.

**Comment by CrustyApplesniffer** [comment]
I've right clicked on the book in the list and chosen "View in Audible"...
This is the link of the page : https://www.audible.fr/pd/Harry-Potter-et-lOrdre-du-Phenix-Harry-Potter-5-Livre-Audio/B06Y5TVGWQ

Is it what you're looking for ?

My windows 10 is set to ENG, but my audible account is french.

**Comment by openaudible** [comment]
That helps. It turns out the author link is captured during the library scan. So rescanning library may fix it.

I'll pull it from the "Book Page" as well, so if you do a "Refresh" on the book it will get updated. 

Thanks for the heads up on language. Theoretically if you set your language to FR you should see google translated UI text elements. Haven't seen any screenshots or evidence it is working. 

Expect fixed in next release. Thanks.

**Comment by CrustyApplesniffer** [comment]
you're welcome
