### ISSUE TITLE
Cannot import part of book

### ISSUE THREAD

**Issue by d-packs** [openaudible/openaudible#159]
Audible allows downloading chapters/parts of books, for larger audiobooks.
These chapters, while downloaded in AAX format, are not recognized by openaudible. I can force import of them by selecting view All files, but when importing nothing is added to the list of books.

**Comment by openaudible** [comment]
A decision was made to only download and process whole books. From there an MP3 can be split using a 3rd party tool (search issues). Didn't want the app to get confused by whole books and partial books and end up with dozens of files for each book when all the info can be in a single file. No plans to fix.

**Comment by seegod1** [comment]
Well that is strange because it **has** been working for me (I download Audible in parts in my Audible desktop software in windows) _all along_, and when it shows up in OpenAudible it's there in the same number of parts as the Audible file.

That is until VERY recently, when I upgraded tp OpenAudible 3.0

Thoughts? I find this disturbing, because some files (like Trinity by Leon Uris) are over a gig in size which is definitely not good for my cell phone's strag space! :-)

**Comment by openaudible** [comment]
@seegod1 The recommended method is to download the whole book using OA. Then convert to MP3 or M4B. Then split by chapter (using the new OA feature) if you really need to. 

Downloading by parts can be done in the web browser, and some OA versions may have let you import them.. but we don't recommend or support that approach. We wanted to create a simple utility that isn't overly complex. And handling audio books that are in one file as well as multiple is a difficult task and could make the user experience (and code!) ugly.

**Comment by seegod1** [comment]
Okay, thanks for your help!
