### ISSUE TITLE
Unable to boot program on lInux

### ISSUE THREAD

**Issue by Gamegenorator** [openaudible/openaudible#160]
I may be missing something but I haven't been able to get the program to boot on Ubuntu, Mint, or Zorin OS. I download the .deb file, install it, and it never appears in the start menu making it unbootable.

**Comment by openaudible** [comment]
Try the .sh installer. All installers are made by install4j. Because they're installed into the /opt directory, sudo is needed.. 

Otherwise, you can unpack either the .deb or .rpm and run the app from the command line, using: 
java -jar OpenAudible*.jar, but look at the README for running from command line.

**Comment by user23498723452** [comment]
I'm kinda a noob with hacking at apps.  Am I doing something wrong here?  @openaudible 


```
$ java -cp /opt/OpenAudible/org.eclipse.swt.gtk.linux.x86_64-4.6.jar org.openaudible.desktop.Application

Error: Could not find or load main class org.openaudible.desktop.Application
Caused by: java.lang.ClassNotFoundException: org.openaudible.desktop.Application
```
