### ISSUE TITLE
Need to change the mp3 bitrate

### ISSUE THREAD

**Issue by MRGEE223** [openaudible/openaudible#220]
32 bitrate mp3's are too digitized for me. (VLC reports a bitrate of "8" for the conversions done by openaudible.)
I would like to be able to switch at least to 96 or even 112/128 for some books.
I saw a closed issue on this, but it never seemed to be solved.
No mention of it in the guide I could find, either.

In order not to post a second issue, I have about 18 red dots in the left field.
It says there is no download link.
The others are working and downloading, but those 18 titles say no link.
I verified that "make sure Audible downloader" check box is NOT checked.
The books I have with multiple download parts seem to be the ones affected. 
Single part downloadable books thus far, seem to work fine.

**Comment by FlorianBeese** [comment]
I guess my topic relates to this, so I will post it in here.

First: Thanks a lot for this nice tool. I just downloaded and installed it and it does the job quite well. What I am missing so far is the possibility of handling the mp3 conversion bitrate.

In the config I stumbled upon a value called mp3Qscale, which is set to 4. This should result in quite good results. Sadly this value is simply ignored by the code according to:

ConvertJob.java:34

final static int mp3Qscale = 6;       // audio quality value 0 to 9. See https://trac.ffmpeg.org/wiki/Encode/MP3

It would be great, if you would make this value configurable, so that everyone can decide themselves, what the right mp3 quality is. This will also resolve MRGEE223 (first) issue as far as I understand it.

Thanks and best regards. Keep on the good work.

**Comment by openaudible** [comment]
I believe that mp3Qscale value in the prefs is being used. Look at the output of the ffmpeg command in the console when a book is converted. 
So to change quality, from prefs, open settings directory. Open prefs json. Quit OA. Edit value. Relaunch. Re-encode 1 book and check for higher quality. When you have a quality you like, you can delete the mp3s and re-convert them.

Let me know what value you're seeing.

**Comment by FlorianBeese** [comment]
Just tested it and it worked. I was quite confused of the low bitrate my MP3s had with the configured value of "4", but it is working. Switched it for testing to "8" and a way smaller MP3 file was created. Actually the resulting bitrate is a bit confusing. For value "4" I get bitrates between 32 and 160 kbits (mostly around 80-96 kbits, what made me think, that the quality setting is "6") and for value "8" I get bitrates between 32 and 128 kbits. According to the docs from the comment in your code I would have expected an average of around 160kbits when using value "4".

Anyway... According to documentation you already set the probably most appropriate value. So nothing to update there. 

I will test a value of "2" for some time and let you know how well it works. Still I would recommend to add the possibility to configure this with a slider (low to high quality) in the UI.

Some info from my first test:
```
AAX size:       435MB  
MP3 Q8 size: 179MB (bitrate 32-128 kbits, avg. ~52kbits)
MP3 Q4 size: 310MB (bitrate 32-160 kbits, avg. ~90kbits)
MP3 Q2 size: 397MB (bitrate 32-224 kbits, avg. ~115kbits)
Length of audio: 7h 41m
```

As the 32-bit mostly occur when the speaker is taking a break, the average quality is higher than stated above (assumption +25%).

@MRGEE223: The reason why you see a bitrate of 32-bit, because the MP3 files have a variable bitrate. In fact your bitrate will be around 100-110kbits in average with the current setting. If this is not sufficient for you, you can change the value in the settings.json file up to zero ("mp3Qscale":0).

**Comment by openaudible** [comment]
Will consider the UI update as a feature request.

**Comment by smikez** [comment]
I have a source and binary patch if anyone wants it. No UI changes, just an environment variable (mp3Qscale) that needs to be setup before launching the app and will override any quality change at runtime.

**Comment by cukabeka** [comment]
Hi, Thanks from my side too! I was totally looking for this tool for ages and now just found it :)

As I tend to optimize my MP3 for space instead of quality, I want to set the MP3 output quality as well - where exactly can I set those environment variables? I looked around in the settings, but could not find anything, and don't know where to dig in the config files (I'm on MacOS).
