### ISSUE TITLE
Unable to Sync library on Italian Audible

### ISSUE THREAD

**Issue by TonioGela** [openaudible/openaudible#23]
As title says, it's impossible to use the italian audible, since a /lib page doesn't exist, even if the log in succedes.

The stack trace in console says
INFO: Page not HTMLPage as expected:class com.gargoylesoftware.htmlunit.TextPage 
Jul 25, 2018 3:54:45 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
java.lang.NullPointerException
	at org.openaudible.audible.AudibleScraper.getAnchor(AudibleScraper.java:331)
	at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:297)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:393)
	at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:46)
	at org.openaudible.desktop.swt.manager.AudibleGUI$2.run(AudibleGUI.java:271)

**Comment by openaudible** [comment]
Can you post the URL you use to view your library when logged in? 
If there are any Italian java developers who want to assist, that would be great. 
It may be that the .it page is just too different to support.

**Comment by TonioGela** [comment]
AFAIK there's no Library page on the Italian Audible (I've visited every other Audible version and where the other have a library button, we have none) but there must be a way to get throught API the library list since we can use the Android app (that this far is the only method I have to obtain a local copy of the book).
So I think that's kinda useless saying you that I'm an Italian Java Developer :(

**Comment by openaudible** [comment]
We removed the Italia option from the drop down. If someone wants it back, they can submit a PR.

**Comment by dmaglio** [comment]
i want to help to add Italian Audible repository

**Comment by TonioGela** [comment]
As I wrote [here](https://github.com/openaudible/openaudible/issues/23#issuecomment-408995514) the /library page doesn't exist on the Italian Audible, t**hing that the Audible Support confirmed me throght a ticket** sadly.
As long as the Italian Audible website remains different there's no way to use OpenAudible with it.

**Comment by g10c0** [comment]
I think I finally found a workaround in order to use OpenAudible for italian users.
I tried it into a windows pc; test have to be done for other OS.

1. you have to download and install Audible app for Windows.
2. then, log in with your audible credentials (you should finally have your audible library fully available and searchable into that app).
3. (_optional_) go to `Impostazioni`(_Settings_)`/Download` and select "**Qualità alta**" (_High quality_), for getting audio file with stereo quality instead of Mono;
4. search for the audiobook you're interested in, click the 3-dots menu on the upper right corner of the little window showing your selected book, then click on "**Scarica**" (_Dowload_);
5. the audio file will be dowloaded into a folder of your PC that can be found going back to `Impostazioni`(_Settings_)`/Download` and clicking where it's written "**Apri la cartella di download nel file manager**"(_Open the download folder into the file manager_); the path could be something like this: 
"`C:\Users\<User Name>\AppData\Local\Packages\AudibleInc.AudibleforWindowsPhone_<an-alphanumeric-sequence-of-13-characters>\LocalState\Content`"
6. select the audio file, drag it and drop into the OpenAudible windows, then let it convert the audio format as set into the preferences menu;
7. you should find the converted audio file into the folder: "`C:\Users\<User Name>\OpenAudible`".

Hope it helps any italian users of OpenAudible.

ciao
