### ISSUE TITLE
Purchase date in list view is formatted with yyyy-dd-mm

### ISSUE THREAD

**Issue by MrEbbinghaus** [openaudible/openaudible#241]
day and month are swapped in the purchase dates in the list view, breaking the sort on this one, while the release date has the correct yyyy-mm-dd format:

![image](https://user-images.githubusercontent.com/2965273/70695423-f56c4200-1cc1-11ea-8561-79f7fca4bbf5.png)

In the detail view for this book and on audible the date is correct.
![image](https://user-images.githubusercontent.com/2965273/70695383-e1284500-1cc1-11ea-83f4-f277607e5a3e.png)

**Comment by openaudible** [comment]
hmm. unfortunately we have to guess at the date because it is inconsistent across regions and book lists. I'll take another look. Feel free to submit a bug report under tools with reference to #241.

**Comment by openaudible** [comment]
So we can get the date from the book list (/lib) or from the book listing. I'm trying to determine if the bad data is from which page-- or both. If anyone sees this, just send a bug report from the tools menu and reference 241.

**Comment by kai-uwe-rommel** [comment]
I'm also seeing this problem (I'm also in Germany) and it is quite annoying.
The problem is still present in the current 1.6.5 version.
The display is inconsistent.
For example, when it is clear what value is the day and which is the month (such as in 2019-06-29, because 29 cannot be the month but must be the day) then the display is correct.
But when it is ambiguous (such as in 2020-02-08, either value is less than 12) then the display is wrong, it is displayed as 2020-08-02.
In the "Audio Book Info" pane the release date is always shown in canonical format e.g. 2018-09-28.
But the purchase date is shown there in "localized format", e.g. 08.01.19.

**Comment by openaudible** [comment]
Ok. Feel free to quit and restart OA. Connect to OA and do a quick refresh (gets first page). Then refresh Info on a book with the problem. Then send a bug report with the Issue #241 and the name of the book that describes the problem. We try to standardize on the canonical format, but when we scrape the audio book page, we must be getting a date we don't like. The bug report will contain a list of your books and the html pages you've recently visited in the OA app.

**Comment by CrustyApplesniffer** [comment]
I think the problem is not limited to the listview but rather to the extraction of data from the website since the format error is already present in the book record.

![image](https://user-images.githubusercontent.com/37656975/77430859-22111900-6ddc-11ea-8478-8fba95f83894.png)

As you can see, the publication date has the wrong format when the purchase date is correctly formatted, but ...

![image](https://user-images.githubusercontent.com/37656975/77431254-b8ddd580-6ddc-11ea-8edb-f5edc428201b.png)

... in the listview, the purchase date is wrong (should be 2020-03-01)

**Comment by Butterfly-Dragon** [comment]
the purchase view is currently missing in version 2.0 if the column is hidden or needs to be selected from a list can't seem to find a way to do it, goold old `CTRL` + `NUM+` seem to not show additional columns

**Comment by openaudible** [comment]
We got a fix for the purchase view coming (we thought that bit of data was removed from audible.. but it just moved to the Book Info page). If you're using a language other than English, I might need the snippet of HTML code (or screenshot) where it says "Added to your library yy/mm/dd" in the upper right of the book information page.

**Comment by kai-uwe-rommel** [comment]
You mean that?

[cid:image001.png@01D6110D.35FDA270]

Mit freundlichen Grüßen

Kai-Uwe Rommel

**Comment by openaudible** [comment]
On a book that you own info page when logged in, it should say something like: to your Library on:
Which in HTML looks like:
```
<span class="bc-text
  bc-size-base
  bc-color-base"  >Added to your Library on:</span>
```

**Comment by kai-uwe-rommel** [comment]
Ok. That’s what I can find:

<span class="bc-text
    bc-size-base
    bc-color-base"  >Titel hinzugefügt am:</span>

<div id="" class="bc-row
    clearFloat
    bc-spacing-top-none
    bc-spacing-none"  style="">
</div>

<span class="bc-text
    bc-color-secondary"  >
      12.04.2020
    </span>
</p>

The date 12.4.2020 is in german format: dd.mm.yyyy

Kai-Uwe Rommel

**Comment by openaudible** [comment]
Perfect. Adding to 2.0.1.  Just need French translation and date format used.

**Comment by openaudible** [comment]
For this to work, you need to be logged into Audible, then do a "refresh book" on a book.. and the purchase date should get added to the book. The date format may still need to be adjusted to be displayed correctly. Let me know.

**Comment by kai-uwe-rommel** [comment]
I just updated to 2.0.1 and see the "Purchase Date" column now.
However, in cases where it is ambiguous, e.g. day between 1 and 12,
the displayed values are still wrong, like in earlier versions.
And in this cases it is consistently always wrong, apparently.

**Comment by kai-uwe-rommel** [comment]
Ah, I see now what you mean. I need to refresh the book info of all books explicitly, even though the information is currently already shown (but wrong).
Did a refresh for all and now the display is correct. Thanks for fixing this!

**Comment by Butterfly-Dragon** [comment]
tried refreshing books and everything. i only have the purchase dates prior to march 15

**Comment by kai-uwe-rommel** [comment]
I took a more thorough look now. The dates are translated correctly for all my purchases in 2020 and 2019 where it was ambiguous. I found mistakes for purchases in 2018 and 2017 where month and date are still displayed the other way around even though I did a refresh on the book. Interesting is that all affected books belong to one series of one author. And for those books also no value is displayed in the Duration column.
I just found that those titles are no longer available in Audible (probably they lost the license to sell it). That explains the issue (no refresh possible) - but OpenAudible could show a warning when attempting to refresh.
Good that I always do downloads and MP3 conversions of all books I buy so that I do not loose it later due to their DRM.
