### ISSUE TITLE
Please add bulk option for splitting MP3 files by chapters

### ISSUE THREAD

**Issue by chuckb7** [openaudible/openaudible#245]
Please add an option for splitting MP3 files into chapters for larger libraries

Either a command line option with mp3 name and destination folder or a standard directory structure and a 'Split All' menu option.

**Comment by milegrin** [comment]
Second this request please.

Possibly add the option to as an option along side the convert to MP3 either in context menu and as auto-function like the current download & convert.

**Comment by sjmiles1** [comment]
I too would like to see this implemented. I just recently began conversion and have hundreds of books available. Having to select source and destination for each book individually is quite time consuming.

**Comment by openaudible** [comment]
Its on the list of future features. I do think a single MP3 is best in most situations... The only good reason I've heard for split by chapter is because some mp3 players have tiny memories and a whole book might not fit. Adding this would not be terribly hard, but then exporting as a web page breaks or would need a large re-write.

**Comment by sjmiles1** [comment]
In my case, it’s definitely more of a player issue, but having them split is the easiest solution. My setup is converting to MP3 to maintain in Plex and then run Prologue on my mobile device to listen. I’ve tested a couple of books both ways, and it appears that Plex handles the individual chapters better than one longer file. I can get through the chapter  separated books and the app(s) maintain where I left off. On the longer books, it winds up jumping around and then it’s harder to find where I actually was. Looking at it again, I think Plex is recording the wrong run length. For a book that’s only 3 hours long, Plex is showing the file at 13 hours.  Like I said, the issue is clearly my setup but this feature would make my life easier.

**Comment by chuckb7** [comment]
It is definitely a player issue for me as well. I have a few different lightweight players that I've tried that don't remember where I leave off from one session to the next. They seem to do better with the smaller files.

**Comment by openaudible** [comment]
There is an open bug about chapter meta data in the mp3 that is makes some apps think the mp3 is longer than it is.. #258 Replacing the ffmpeg can fix that bug but might introduce other known bugs. 

I am adding the request to the nice to have feature list.. but if your audio player can't remember your last played position, going back to the previous chapter doesn't seem like a good solution.

**Comment by RocketLaser51** [comment]
Feb 7, 2020. The current mp3 chapter splitter is good, but it creates mp3 files with metadata that reliably crashes Windows Explorer in Windows 7.

Granted that this is an obsolete OS, but metadata so seriously non-compliant should be considered a bug. In a perfect world, the attributes such as name, artist, album, genre, year and cover image should be inherited from the parent file.  For now, I have to manipulate the files using cmd.exe.

**Comment by openaudible** [comment]
@RocketLaser51 We recently upgraded our ffmpeg so perhaps the crashing windows 7 has been fixed.
Will close and mark this issue as a feature request.
