### ISSUE TITLE
mp3 to m4b

### ISSUE THREAD

**Issue by danielb2** [openaudible/openaudible#273]
Seems m4b support [isn't forthcoming](233) and like many others, I'm in a position where my audiobook player does not support whatever chapter information is stored in the mp3.

Does anyone have a tool to extract the chapter info (ffprobe -v quiet -print_format json -show_chapters <mp3) and convert it into an m4b ?  including the cover too

**Comment by Geordon** [comment]
I use Adapter by Macroplant to convert from MP3 to m4a, then just do a mass
rename from m4a to m4b, since they are essentially the same format.

—
Geordon VanTassle

On February 19, 2020 at 2:08:38 PM, Daniel Bretoi (notifications@github.com)
wrote:

Seems m4b support isn't forthcoming <233> and like many others, I'm in a
position where my audiobook player does not support whatever chapter
information is stored in the mp3.

Does anyone have a tool to extract the chapter info (ffprobe -v quiet
-print_format json -show_chapters <mp3) and convert it into an m4b ?
including the cover too

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openaudible/openaudible/issues/273?email_source=notifications&email_token=ABK7RCBW2GXHOJJYWR52NELRDWGULA5CNFSM4KYA2CHKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IOYFXXQ>,
or unsubscribe

**Comment by danielb2** [comment]
Seems this is the best solution for me currently:

Using [fish](fishshell.com)
```
function aax2m4b
  set artist (ffprobe $argv 2>&1 | ag artist | head -1 | sed  's/^.*:[ ]*//g')
  set album (ffprobe $argv 2>&1 | ag -v album_artist | ag album | sed  's/^.*:[ ]*//g')
  set date (ffprobe $argv 2>&1 | ag date | sed  's/^.*:[ ]*//g')
  set folder "$artist - $album ($date)"
  mkdir "$folder"
  set output "$folder/$artist - $album ($date).m4b"
  ffmpeg -activation_bytes <code> -i $argv -c copy $output
end
```

That's nice about openaudio is that it doesn't need this activation_bytes business to be figured out

If anyone cares I got the activation_bytes by using https://github.com/inAudible-NG/tables
Not having linux/windows, I used docker inside the cloned tables repo:
`docker run --rm -it -v (pwd):/root ubuntu`
And then running `/root/rcrack` inside it.

**Comment by danielb2** [comment]
Any chance we could get openaudible to do this kind of nice output ?

**Comment by openaudible** [comment]
This has been discussed in a number of issues. M4B has a maximum size that makes it unsuitable for whole books. The chapter data is in the mp3. You could petition the audio book player you're using to read the mp3 tags. People interested in this topic can still search through the issues to find your solutions/suggestions.

**Comment by openaudible** [comment]
M4A support has been added to 2.0.6 and newer.
