### ISSUE TITLE
Minor bugs (v2.0.3) Windows 64-bit version

### ISSUE THREAD

**Issue by orish1** [openaudible/openaudible#333]
So far, I've seen the following faults or bugs:

1. The full audible library doesn't seem to be properly detected. It's hard to say, but the number of files To Download doesn't seem to match the list of books in the library. 

2. The figures are truncated in the Library Status block (see attached file)
![OpenAudible layout](https://user-images.githubusercontent.com/13717719/80184776-6559e400-8635-11ea-80fd-b5aa12cb89aa.png)

Notice it says To Download: 0 (I selected all books to be downloaded and I also set automatic download in preferences) - but the books do sometimes seem to download.

2a. Do the downloads or other actions only happen when OpenAudible has focus, or does it run in the background? Nothing seems to happen for 10 or 20 minutes, but if I then switch to the app and click somewhere then the display changes.

3. The title headers (Books, Hours, MP3 Files, etc.) seem to be clickable, but it's not obvious. Make them into buttons or toggle the font or something so you know which panel you're looking at. (Having status=Books in the search bar is completely meaningless. How does anybody know what is supposed to go into the search bar anyway?)

You can also click on Connected, Region, Hours, etc. but although the app seems to respond in some way, nothing happens.

4. When I click on Books, I get the list of books in the audible library. When I click on To Download, I get a blank list - even though it seems as if the books are downloading. Ignored is 0 also, and the list is blank, but I think there are about 30 or so books that are undownloadable (freebies or one-off shows on audible).

Or are they? Even with the preferences set to auto-download, it doesn't look as if anything is being downloaded!. There's a status icon on the left column of the list of titles. This is very useful :)

But it doesn't match the Library Status figures.

5. The current and total amounts in Downloading / Converting are wrong / truncated. As you see, it says
Downloading 3 of
Converting 3 of

It should be something like 
Download 185 of 343
Converting 60 of 343

6. The menu option to send bug report is kind of useless, because you need to enter a Github number. Well, there isn't one - so you have to sign in to github.com manually to create an issue in order to send the bug report. Perhaps generate a number automatically...?

7. Github doesn't support the internal browser, so either don't go to github.com from the internal browser and remove the feature, or fix the compatibility issue so that you can send a bug report from within the app.

8. Region seems to a bit odd also. It correctly states that I'm signed into Region UK, but does that also specify the region of the book? I have some books from the audible.com (US), most from audible.co.uk (UK) and a few from audible.fr (France). This is probably not important because, once downloaded, it really doesn't matter which marketplace it was purchased from.

**Comment by orish1** [comment]
Pont 5. Oh, well this display error seems to have rectified itself:

![OpenAudible layout 2](https://user-images.githubusercontent.com/13717719/80190380-6e02e800-863e-11ea-8415-a6e6aeebcd90.png)

I just left it running for a while and I noticed that the display changed by itself.

However, the number of files To Download, Downloading and Converting all seem to be wrong. There are about 250 files in the download queue, so instead of displaying 3 of 246, shouldn't it be 250 of 343, or perhaps 250 of 300, assuming 43 books are already downloaded???

etc.

**Comment by openaudible** [comment]
Hey.. Appreciate the feedback. Thanks.. Reviewing and will respond. There is room for improvement.

1. Go with the Books count to see how many books you have available. The other stats will make more sense when you're done downloading/converting everything.

To Download means: files that can be added to the download queue that aren't already in it. Makes it easier to select just those books so you know which you can download. 

2. Weird about the width of the Library Status. We tried to give plenty of room.
2a. Conversion/downloads keeps going in the background. Stats should update in real time. Click on a book that's downloading or converting and you'll see the status update in the book info.
3. Good idea. Wanted to keep the UI clean and programming simple. Maybe a drop down would work where the search is. 
4. Maybe need one more status for "Not Downloadable". Ignore is something you have to do to a book to have it be hidden.
5. We'll agree it can be confusing. But once all your books are downloaded and converted, it makes more sense. 
6. Bug reports don't need an issue. They just help tie a report to an issue.
7. Yeah, the browser is not for general purpose use. We may use the user's regular browser for documentation and "home page" links.. but just more code to cross-platform test/maintain.
8. Multiple regions is tricky. Audible doesn't like you switching between them. 
5 revisit: Accounting may be non-intuitive. Once downloaded, a book doesn't show in the doesn't show in the Downloading stats, but the number of AAX files would go up to balance the account.. but we don't show that number (any more) because it isn't that useful.  The 3 is the number of concurrent jobs.

**Comment by orish1** [comment]
Point 5 - problem again. It's a different problem each time. Now it's displaying:
Downloading: 3 of 10 (when it should be 3 of 160... or maybe it was something like 109)

It's now below 100 and is displaying:
Download: 3 of 53

(very strange)

**Comment by openaudible** [comment]
Added to the documentation.
