### ISSUE TITLE
Missing Book info

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#340]
I have 48 books for which Openaudible cannot gather purchase/release date, as well as much other information.

![image](https://user-images.githubusercontent.com/33538906/80858787-efb8ce00-8c5b-11ea-80d0-35dc4401633f.png)
In the image above the books are ordered by "purchase date" therefore the books are grouped, i highlighted a strange case (rather hilariously the book appears to redirect to the version that people can buy nowadays but which is not the one in my library. So it does not appear to be "purchased").

This is because from what i understand openaudible tries to get the info from the page of the book, and due to licensing those books with missing info are not available anymore to buy in my country.

You can obtain partial info (most stuff that is missing from the columns) from the library page (which also still allows the books to be downloaded)

I cannot understand if this is by design and should/could be corrected (or not) or if there is a setting i ticked and forgot about it.

**Comment by openaudible** [comment]
When you're logged in (as you were in your image) you should be able to select any book without a purchase date and select Action: Refresh.  So you may need to "select all" and refresh all the meta data.

**Comment by Butterfly-Dragon** [comment]
that... is exactly what i did, several times.
It does not show the info.
For the reasons i described.

**Comment by Butterfly-Dragon** [comment]
Please re-open this issue.

Since you did not believe me, and classified me as "yeah, yeah, you are not doing this right" without reading what i wrote...

Here is what says the log when i try to refresh the info of the selected books (i selected the books with the missing info, right-clicked and then told it to refresh the info, since you did not fix the problem where keyboard shortcuts are not picked up yet, but i see you closed that issue too)

[log.txt](https://github.com/openaudible/openaudible/files/4569587/log.txt)

**Comment by openaudible** [comment]
I closed the issue because I wasn't sure what your bug was and couldn't reproduce it. OK to request it be re-opened. 

It looks like those books without a purchase date are not available in audible, or the product ID, ASIN, URL or something else changed. 

If you select a book without purchase date, for instance The Spiderwick Chronicles I, then do a  "View in Audible" you're supposed to see the book info with purchase date. Looks like you see a "Shucks. This product isn't available." which is why OA can't determine it. 

From OA: go to: 
https://www.audible.com/library/titles?searchTerm=Spiderwick
and do you see your book there? Compare the URL for that book with the one OA is using:
https://www.audible.com/pd/The-Spiderwick-Chronicles-Volume-I-Audiobook/B002V0QXFS


OA is supposed to get the correct URL for your book. However, IF that book isn't in your library AND the URL has changed, OA will not be able to get the purchase date (and duration).

**Comment by Butterfly-Dragon** [comment]
**PLEASE READ THE ORIGINAL POST!

I already answered all that in the original post!**

![image](https://user-images.githubusercontent.com/33538906/80933485-3b868700-8dc4-11ea-87f9-ab67e6b4eb81.png)

Audible has this licensing stuff where books appear and/or disappear from view based on licensing.

I can totally **__still download__** those books, but they are not available anymore from the book page. **__ONLY FROM THE LIBRARY__**.

Not only that, one book in particular gets "redirected to a different version of itself" so it appears as if i did not buy it.

**Comment by openaudible** [comment]
We do our best to answer questions. You're right. You did say the book was no longer available in your library and that some books redirect you to a new page but doesn't show as purchased. 

But that is exactly why the "Date purchased" and other information is blank. Audible has removed that information. 

We don't have a meta data editor (yet). You can export to excel and enter the missing data manually.. or edit the books.json file if you want. But if Audible doesn't have a page with the date purchased info,

**Comment by Butterfly-Dragon** [comment]
I was about to remind you that the library page has those info... but then i just went there and i saw the "new and improved" library page is missing all those info.

Thanks audible! 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

This is so frustrating.
