### ISSUE TITLE
Question about file size difference

### ISSUE THREAD

**Issue by ALB-2** [openaudible/openaudible#361]
Benjamin Franklin: An American Life
By: Walter Isaacson
Narrated by: Nelson Runger
Length: 24 hrs and 40 mins

I downloaded it and noticed OpenAudible says the file is 24:42 in length.
However the file size is 678,085 KB and Windows says the length is 65:19:11.

I opened the file in Windows Media Player and went to the end of the file and it also said over 65 hours.

???  Why is the mp3 file so huge when it should be less than 25 hours long?
I am using OpenAudible version 2.0.7 and I never notice file size problems before upgrading to this version.  I am not sure if this is an issue with OpenAudible in general or just this particular book.

I just wanted to touch base with the creator and github seems to be the only way.

If I have done something wrong, I apologize.

**Comment by openaudible** [comment]
Many audio players are not able to easily calculate the duration of a variable bitrate mp3. If you open the file in VLC, you will see the total duration change as VLC calculates the duration.  Because the mp3 bitrate it is variable, a program can't reliably just multiply the bitrate by the amount of data.


So, the answer is.. yes, its a known issue.. But it is a limitation of large mp3 audio files and shouldn't affect playback. The audio portion should be fine (its starts at the beginning, ends at the end, and has no extra audio added!)  

And 700K for a 25 hour book is reasonable. It should be a bit smaller than the AAX on quality 4. 

So will close assuming the audio is fine.. just calculating the duration is tricky for computers.
