### ISSUE TITLE
Books not downloading since audible plus

### ISSUE THREAD

**Issue by bitternight** [openaudible/openaudible#440]
My books purchased after audible plus was implemented will not download to be converted.

**Comment by unitof** [comment]
Dang, can confirm. `Connect Audible` loads the new https://www.audible.com/library/titles page, but doesn't parse anything. Page just loads and sits there.

**Comment by openaudible** [comment]
What region are you in? I haven't heard about Audible Plus and our tests continue to pass. Is there a "Download" button next to each title? Does clicking on that add the book to the library? 
If you can send a bug report from the About menu after trying to do a Quick Library sync, that'd be great. Just reference 440.

**Comment by unitof** [comment]
Oh, interesting. I'm in USA. Audible Plus had a big launch last week here—it's basically a bunch of "Audible Original" content is now all freely available to members, instead of only allowing 2 per month from a rotating selection. The site did also seem to get a bit of a redesign:

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/2448782/92038951-3b7e9f80-ed42-11ea-9b71-584f83922901.png">

Above is the new Library page. Most of the `Download` buttons simply begin the download. But for items with multiple formats (such as Single- or Multi-Part versions) it opens a dropdown on hover, as pictured for The Dark Forest in my screenshot.

Trying to connect Audible (Command + K) just opens this page and loads indefinitely. Note the pink bar at bottom right.

I've waited a while but never get an error or timeout. It seems it's just never finding whatever it's scraping for.

I'll send that bug report though shortly, and if helpful can also send you an HTML export of the https://www.audible.com/library/titles page I see.

**Comment by openaudible** [comment]
OK, good to know about the hanging bug. Mac only? Anyone seeing this on Windows or Linux? 

Saw one bug report (probably yours).. but unfortunately it doesn't show the html of the library page.. probably because it hasn't finished loading. 

On windows you can hit "F12" to get the browser debugger up and you might see some error messages. 

I'll fire up the Mac and try to reproduce.

**Comment by bitternight** [comment]
I am using windows 10 and I am having these issues.  I'm in US.

**Comment by unitof** [comment]
Hm, it’d been sitting for well over a minute.

Maybe there’s some new ongoing open request or socket that tricks OpenAudible into thinking the page never completed loading. That could be the issue.

I am on Mac but will see if F12 opens a debugger console tonight.

**Comment by openaudible** [comment]
I can't reproduce on any of my machines.. Would be nice to know what network connection is hanging. The "F12" debugger can show network connections. Maybe one is going to an advertising or tracking site that is either blocked or offline? I can try to add some extra browser debugging code into the next version.. but would love to get more data about what's going on.
Thanks in advance

**Comment by bitternight** [comment]
Specifically, any of the books I've purchased after Audible plus went live will not download. All the other books download fine. The newest books just sit in the download queue and do not get downloaded at all. I'm not sure how to do the f12 debugger. I tried to press f12 when the browser was open but nothing happened. I'm not super programming literate. I just noticed that it's not working anymore.

**Comment by openaudible** [comment]
That's a strange issue. Unable to reproduce. 
Can you:
Restart OA
Open Console Window (CTRL-D)
Select one book to download
Select Action: Download
See if the progress shows it is downloading or if there is an error.
If no progress or an error, or it "just hangs", send a bug report from the About menu and say 440 / book won't download.
I'll get a copy of the log and see any errors you're seeing.
Check your anti-virus to make sure OpenAudible is allowed to access the internet. (maybe do that first!)

**Comment by unitof** [comment]
Update on my end (macOS, so neither `F12` nor `Ctrl+D` nor `Cmd+D` bring up anything):

After letting `Connect to Audible` load and sit a while as above, I just closed the window. It never confirmed it connected my account, but now downloads *do* work, including downloads of items I purchased after Plus launched last week.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/2448782/92256954-6d0e7c80-eea2-11ea-92be-1eff7f817ed0.png">

One thing to note is that the `Purchase Date`s are missing for anything purchased after Plus launched: perhaps that's a clue?

Also, I don't think you can download audible that *is* Plus content. I cannot confirm this though, as I just paused my membership, so all Plus content in my library is unlistenable no matter what (see the red status icons).

**Comment by rloomans** [comment]
Plus content doesn't download. It shows up in your library pages with only "Listen Now" and "Remove" buttons, rather than "Listen Now" and "Download".

**Comment by Mantene** [comment]
> Plus content doesn't download. It shows up in your library pages with only "Listen Now" and "Remove" buttons, rather than "Listen Now" and "Download".

Yep, I have tried manipulating the download link of another book to use the information of a Plus book. I get a file that says the book is not in the user's library. There is, of course, an aax associated with the book since my iphone can download it via the app and you CAN buy the book if you really want to, but it appears that without the Audible mobile app there is no way to download the file.

**Comment by Talidorn** [comment]
I believe that the issue might be, on Windows, that the new Plus content isn't playable on Windows.  Here is the link that made me think this might be the case https://audible.custhelp.com/app/answers/detail/a_id/10191/kw/windows%20app  

The solution might be to find a way to access the content via the Cloud Player on the Audible desktop site.

I'm guessing they don't want openaudible to allow us to backup our library of "free" (at $7.95/mo) books.

**Comment by openaudible** [comment]
Yes, and that's correct. Only audible content you specifically purchase can be converted. Podcasts and additional free content is not supported. Thanks for the heads up.
