### ISSUE TITLE
No license code received after paying

### ISSUE THREAD

**Issue by abwaleson** [openaudible/openaudible#444]
I paid for this, but haven’t received the license number so I can actually use this. Please fix asap. Thanks in advance.

**Comment by openaudible** [comment]
The most likely problem is that our payment processor rejected the order due to anti-fraud concerns and didn't properly give you a good error message or explanation. The charge may show as "pending" but will soon be removed. You can try again or contact fastspring.com order support. Sorry for the trouble...
