### ISSUE TITLE
FFMPEG Patch for AAXC Compatibility - Please Implement for Import!

### ISSUE THREAD

**Issue by GeniusCrimper** [openaudible/openaudible#450]
https://ffmpeg.org/pipermail/ffmpeg-devel/attachments/20200408/eeb2c4e1/attachment.patch

**Comment by GeniusCrimper** [comment]
Thank you for reading, and thank you for your great software!

**Comment by openaudible** [comment]
Thanks for the heads up. I'm not sure it makes much of a difference yet. If you tried to import an AAXC file, it would still fail without knowing the secret keys. The secret keys are only available if you use another app that creates an API connection to audible. Will keep an eye on things. Closing, but feel free to add comments etc.

**Comment by PacoBell** [comment]
audible-cli has apparently been able to [do this](https://github.com/mkb79/audible-cli/commit/ddf84febdbf4eb29cc4f8d290919db5a1e71f19d#diff-c77b346fcf936c22aab59967f38974cecf0387c7929379e3a1846c1d7e2d87a7) since Jan 28, 2021 with the downloaded voucher file and the patched ffmpeg. Wanna take a crack at porting it to openaudible?

**Comment by openaudible** [comment]
@PacoBell That sounds promising. Thank you for the link. Still on my radar. Will need to find LGPL versions that have the patch. We are more of a java shop, so not totally sure how the cli code works. Offering to help?
