### ISSUE TITLE
Audible Plus Catalogue

### ISSUE THREAD

**Issue by andrewcroberts1** [openaudible/openaudible#460]
I have successfully downloaded the files via my fire tablet and saved them on an sd card.  
I have attempted to transfer these .aax files to the open audible system, but in so doing, they show up in the open audible manager, but when I attempt to convert them I get the invalid key for hash =...............

![Capture](https://user-images.githubusercontent.com/72048398/94488125-0d10aa80-01b0-11eb-9ad2-8dc45117b278.JPG)

I would like to be able to download my audible plus books and then convert them.  What is causing this to be an issue?

**Comment by Butterfly-Dragon** [comment]
Can confirm.

On the web page you only have "play" but not "download"

Also: Same is true for podcasts.

I subscribed to a free one to see if i could get it.

Have never been able to listen to it.

https://www.audible.com/pd/Audicted-to-Sci-Fi-Podcast/B08DDFVSKL

They do not have a "download" button though. Just a "Listen" one.

So i guess they are tied to your subscription and if you cease your subscription you waiver your rights to listen to those things you got for free...

...i guess they could be considered "incentives to keep paying" the problem comes when you wish to buy something you got for free "by mistake" since then that option is forever gone.

**Comment by andrewcroberts1** [comment]
Any other thoughts from others?  It has been suggested that I need to find the hash key for the file, and then use ffmpeg to convert it.  But I am not technical enough to follow some of the instructions out there.  Any help would be appreciated.

**Comment by openaudible** [comment]
Currently there is no support for adding books that you did not purchase. OpenAudible is only for backing up your books you currently own. 

Our understanding is that these books use AAXC encryption, which require a special keys to unlock. Even if we could decrypt them we would need the keys, which we wouldn't be able to get.

**Comment by Butterfly-Dragon** [comment]
yeah, i was just miffed that my "subscription" which always came with books all of a sudden came with books i don't own anymore.
