### ISSUE TITLE
"Windows protected your PC"

### ISSUE THREAD

**Issue by zylstra** [openaudible/openaudible#466]
I get a "Windows protected your PC" dialogue box alert when I attempt to install Open Audible. The box says further, "Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

Why does this happen?  I have not seen this alert before.

**Comment by openaudible** [comment]
It just means we don't have a valid code signing certificate. You'll just have to confirm that you want to run the installer/application. 
We have 830 stars on github and lots of good press you can google. So its a risk to run any application that has that message, but we can promise nothing bad will happen. (Assuming you download it from our site or this github releases page. )

**Comment by zylstra** [comment]
OK, thank you.

**Comment by tharlar** [comment]
I don't believe that.

**Comment by openaudible** [comment]
We have since gotten a valid code signing certificate. It should say signed by Olivia and be a valid code signature.  
However, you may still get a warning about it potentially not being safe in Windows. If that happens, you can get more details and if it says it was signed, it is OK to "run anyway."
