### ISSUE TITLE
Allow specifying a file name pattern for converted files

### ISSUE THREAD

**Issue by haumacher** [openaudible/openaudible#477]
Hi, I like to archive my books in a separate directory structure. For that it would by great, if I could specify the file name for the converted (e.g. M4A) files. Currently the file name is only the title of the book. It would be great, if I could specify a file name pattern for the generated files, e.g. "%T - %A [%Y]" for naming the files "title - author [year of release date]". What do you think?

**Comment by markfaine** [comment]
I would second this request and also ask that folders be supported such as:
%A/%T/%F 
for 
John Smith/Book Title/File Name.m4a
or something similar.

**Comment by openaudible** [comment]
Its a good suggestion that has been suggested before. 

Not sure what happens when you change the setting -- do all files get renamed and moved to a new location? 

Unfortunately, it gets tricky when books have similar titles and "collide"... also also file names often can't contain some common characters (especially on Windows -- ?, *, <, >, etc. which make things tricky)

Thanks, and marking as "feature request".

**Comment by haumacher** [comment]
Was this closed by accident?

I think it is ok, if only new books are affected by changing this setting. The resulting name could be stored in books.json.

What's the current policy with colliding titles? It would be acceptable, if the pattern must contain at least author and title

**Comment by markfaine** [comment]
I have seen other software that does this. It's usually handled as one or the other as a rule, or there is a flag that is user selectable. I prefer to overwrite though others may not so an option to overwrite existing files would be probably the best way to handle it.
