### ISSUE TITLE
OA Version 2.4.1.5  Beta Link to Narrator on "Show Image" Page

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#553]
The only item not working as expected is the link to Narrator in the Info column when using the "Show image" view page.  In all cases this link is filled in with a link to the Author, not to the Narrator.  Note that both links works are populated and work correctly in the view where "Show Images" is not selected.

**Comment by openaudible** [comment]
Oh I think you mentioned that earlier. Will fix. Also hoping to get the header looking better.

I think also, to clarify your earlier report about logging out etc. the quick sync is really quick. It should only look for new books added since the last time there was a sync. So after you buy a new book.  Full resync should update ratings and add any new books. If you notice anything that involves having to log out, let me know.

**Comment by openaudible** [comment]
Fixed for next release. Closing.
