### ISSUE TITLE
Noise

### ISSUE THREAD

**Issue by gtoc12** [openaudible/openaudible#610]
Noise is produced on some AAX to M4B conversions. No obvious connection as to which files will have issues. Constant scratching noises overlaid with the audio. Has happened on 5 out of 40 audiobooks

**Comment by openaudible** [comment]
If you convert to mp3 do you get the same issue? Have you tried other players? (Like VLC)

**Comment by gtoc12** [comment]
I have not tried to convert to MP3 yet, mostly as it takes so much longer And I specifically want M4B due to chapters etc. It’s why I got OpenAudible.   
  

  
More detail:
  
They play fine as M4B on Apple Books.   
  

  
However when played on a 5th gen iPod there is a constant scratching noise throughout.
  

  
I have deleted, redownloaded and re converted the files in question. The scratching noise occurs every time but only on the iPod. The other M4Bs all converted in the same batch all work fine.   
  

  
I can see no connecting factor between the ones that have issue. Most have _ep6 in their file names but not all. The originals from
  
Audible were all created across multiple years so it’s not a new vs old DRM issue (ie. some are from early 2000’s, some are new).
  
They are of differing lengths so does not appear to be a size issue as I have larger files which play fine from the same batch of conversions.
  

  
I can only describe it as truly bizarre.   
  
  
  
  
  
    
  

  
  
>

**Comment by openaudible** [comment]
Sounds like a bug on the iPod. Check for a firmware update using iTunes, or check https://www.felixbruns.de/iPod/firmware/  Or track down a newer iPod. 

Probably a sample rate or compression setting that wasn't fully tested (since there weren't a lot of m4b files available back when it was created.) 

I'm guessing mp3 would work. (It has chapter data, but most players don't yet parse-- need to submit feature requests to handle mp3 chapters.)  

I'm going to close as "not my bug", but feel free to search around the ffmpeg forums and if you find anything, let us know.
