### ISSUE TITLE
[FR] - Separate blue labels for "Active Downloads" and "Queued"

### ISSUE THREAD

**Issue by xaeiougit** [openaudible/openaudible#698]
Clicking on the "Downloading" label in the "Library Status" panel shows the 3 books actively downloading and also those queued for download.

Unless I'm missing something, the only way to see which books are actively downloading is to take a peek in  OpenAudible/tmp/ for partially downloaded files and then click on those books to see their progress in the "Audio Book Info" panel.   The books do not appear to be downloaded in their order in the bottom panel.

If you created blue labels for something like "Active Downloads" and "Queued" in the "Library Status" panel I think monitoring progress would be a lot more intuitive.   Right now the only indication if downloads have frozen is your "Downloading" blue label just stops decrementing (M4B file counts freezes, and the number of green dots in the bottom panel also freezes, but these don't really give an instant sense of progress).

**Comment by openaudible** [comment]
Interest FR. The books are converted/downloaded in the order that they are added to the queue. 
We don't have much more vertical space to add two more entries (queued/in progress), since we are trying to keep it small so the book list is as big as possible.. But a different image would be simple. 
You can click on a book that is downloading and see the progress in the book status page. Obviously books shouldn't get stuck downloading.

**Comment by xaeiougit** [comment]
Another option which wouldn't use any extra space in the panel would be to make the two numbers clickable, eg "3 of 237" to bring up either the list of books actively downloading (3) or those queued (237).

**Comment by openaudible** [comment]
In 3.1 post just now!
