### ISSUE TITLE
Refreshing info of a download book raises an error

### ISSUE THREAD

**Issue by CrustyApplesniffer** [openaudible/openaudible#74]
There are audio books I cannot refresh info.
When I select a audio book in the list and right click on it, a popup menu is displayed.
I choose the `Refresh Info` menu item and a error is displayed (see below)
![image](https://user-images.githubusercontent.com/37656975/50009660-cb514880-ffb7-11e8-95c2-6a716ed2142d.png)

In the console I can see the following information:
```
déc. 14, 2018 3:47:59 PM org.openaudible.desktop.swt.manager.AudibleGUI showError
SEVERE: refreshing book information
java.lang.Exception: product id mismatch for Le Hobbit and Le Hobbit
	at org.openaudible.convert.AAXParser.updateBookFromAAX(AAXParser.java:327)
	at org.openaudible.convert.AAXParser.update(AAXParser.java:316)
	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:663)
```

**Comment by openaudible** [comment]
I will update the error message to display more details.. but it may be that you have two books with similar (but different) product id's. The software is saying that it won't update the meta data from the aax file into the current book because the product id's don't match-- preventing book A's data to be merged into book B.... If you ran earlier 1.2.8-1.2.9 versions, you may want to erase or move your books.json file and try re-running the app.

**Comment by CrustyApplesniffer** [comment]
You're right, I removed books.json and all is correct now
