### ISSUE TITLE
Missing Images when importing M4a

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#762]
On Mac Version 3.2. I am trying to recreate the web page, I import a bunch of previously converted M4a books - Many of them do not show the image on the web page, even though the image is visible on the OpenAudible for the same books in the OpenAudible control panel.   This was previously working fine in earlier versions.  Can you fix this please, I have an additional 900 or so previous conversions to import!

**Comment by oboe45** [comment]
#762 - This applies to previously converted M4b files too

**Comment by openaudible** [comment]
Are the filenames the problem --- quotes, unicode, or something else?
Is there an image file created and copied to the web directory and the link is just wrong?
Will start soon.

**Comment by oboe45** [comment]
I dont know the problem, I am just a licensed user trying to use software
that worked perfectly well before version 3.2.

The files mp3, m4a and m4b are all versions created from previously
downloaded aax files.   I can see that the images are embedded in each
file, i can also see that the file names generated from previous downloads
are often not the same as the filenames on the Audible site, it seems that
the download (or something else in 3.2) edits the filename to exclude
punctuation and to reduce the file names to shorter forms - no idea why
this was done, it all worked well before!

The problem with this mess is that I have a complete set of AAX files
downloaded earlier in the year, I have a set of m4b  files that were
generated by openaudible conversions either from imported aax or downloaded
aax files - these all worked perfectly in the versions before 3.2.  Now I
have duplicated fies (but with different file names), unattached image
files and a useless web site with more than 1800 entries when it should
contain half that number.

I have spent hours getting this set of files and web site to work as a
useful repository to support play back on any of my apple machines, and to
work well with the in house audio players and with portable players - its
now back to an unusable mess.  Download from the Audible site took days and
days when I first set this up, I hope that the solution does not involve a
download again and that the set of AAX files previously downloaded are
useable, else goodbye OpenAudible.

**Comment by openaudible** [comment]
Confirmed issues with images showing on the generated web page. I have a fix. Looks like we are not handling the single quote characters correctly.. but trying to figure out if that is because we changed our file naming, which could introduce duplicates. 

Downloading again shouldn't be needed. 

One thing we are thinking of doing is removing support for m4a and renaming all m4a files to m4b. (No other change-just the filename extension changes.) But haven't figured out the best strategy. Giving you a heads up. 

The filenames are tricky because if you want the files to work on windows a number of file name issues can come up-- illegal characters, multiple spaces and dots are illegal, etc. So we try to pick a name that makes sense. 

While its a pain, you may need to wipe the web directory and re-generate it from scratch. At least no encoding or downloading--just copying.. and of course, we're in the process of combining the library and web into the same directory so that (if you want) you can avoid a lot of duplicate files on the disk. Trying to move carefully so as not to break things, but obviously we're still breaking things.

**Comment by oboe45** [comment]
thanks, I will wait for the image fix and the single quote issue - my plan
is to wipe everything and import the AAX files I have downloaded, then
convert all to M4b - its a slow process with a 1000 AAX files, but faster
than fresh download

**Comment by openaudible** [comment]
Ok. Posted a new prod version. Hopefully will keep the downloads to a minimum. Possible that re-converting could improve chapter names... but who knows.
