### ISSUE TITLE
Chapter Metadata: Every chapter now has a prefix: 1, 2, 3 and so on...

### ISSUE THREAD

**Issue by tylernguyen** [openaudible/openaudible#784]
Hello,

OpenAudible already pulls chapter metadata titles from Audible. So there's no need to prefix each chapter title with a number. Doing so only makes it more clunky. In addition, the newest update somehow makes it that OpenAudible no longer pulls the : from the chapter medata.

**Comment by openaudible** [comment]
Is this behavior when you split a book?
We are supposed to add a prefix only when the chapters aren’t sorted alphabetically. Otherwise your book player won’t know which order to play them. 

if not talking about splitting, we don’t (shouldn’t) modify the chapter from what we receive. You can look at full meta data in get info under the report tab.

**Comment by tylernguyen** [comment]
Yes, it happens when the book is split.

There should already be tracker numbers. So I don't think the prefix is neccessary.

**Comment by openaudible** [comment]
Sometimes there is an preface or epilog that messes up the sorting. In which case we have to add the prefix to all. Feel free to send a list of the chapter names from the book report.

**Comment by tylernguyen** [comment]
@openaudible 

Sorry for the late screenshot. Here's the list of chapter names.
![Screenshot 2021-11-23 181112](https://user-images.githubusercontent.com/3349081/143148314-afb36576-5ac2-4311-b417-f743971c88ac.png)

The only thing that's there is the opening credits. Is there a way to program common titles such as Opening Credits, Foreword, and such into OpenAudible when splitting so that prefixing the chapter title is not neccesssary. As it stands, I have to manually edit the titles before putting these books into Plex.

**Comment by openaudible** [comment]
Yeah, there are several files out of alphabetical order.  This is non-typical chapter naming. 

We don't recommend splitting books into multiple files in the first place, since nearly all players can handle large m4b files that contain multiple chapters. 

We added splitting as a "nice to have, easy to implement" feature that has been a source of many headaches.. 

This isn't likely to be fixed.
