### ISSUE TITLE
Conversions on M1 take a very long time...

### ISSUE THREAD

**Issue by Ratatinator97** [openaudible/openaudible#831]
Hello,
Not a real issue here but I was just wondering why the AAX to MP3 conversion with ffmpeg take a lots of time with the M1. Is it because ffmpeg isn't native ?
Anyway, congrats for this great tool !
Alex

**Comment by openaudible** [comment]
Yeah, m1 support in ffmpeg doesn't appear likely any time soon.. We use these (great) guys to build our binaries. https://evermeet.cx/ffmpeg/apple-silicon-arm
If anyone finds a good static LGPL version of ffmpeg/ffprobe for m1 silicon chips, let me know. 
Thanks for the kind words!

**Comment by openaudible** [comment]
Looks like supporting m1 is possible. Did a test and we see 4x improvement on mp3 conversions. Will explore.

**Comment by openaudible** [comment]
Latest beta has a silicon version!
https://openaudible.org/beta
Check it out!

**Comment by alzxjm** [comment]
Hey - downloaded the beta version on my Apple Silicon device. I get a "Error converting: ffprobe error" when trying to convert books. I have ffmpeg v4.4.1 installed on my device, if that matters.

**Comment by openaudible** [comment]
Hmm. OA should use internal ffmpeg build built for M1. It’s possible we didn’t make a fully static build. Can you send a copy and paste of the console log for that error ( you can edit to hide user name or book info etc.)

**Comment by openaudible** [comment]
Anyone else having a problem with beta for Apple Silicon?

**Comment by openaudible** [comment]
Was just able to confirm this. Looks like a library needs to be statically linked. Stand by.

**Comment by openaudible** [comment]
Posted new beta 0.7 for m1 macs.

**Comment by openaudible** [comment]
3.4 and higher should have support for m1 macs! Big speed improvement. !!

**Comment by oboe45** [comment]
I was dumb enough to buy my Mac Pro just before they started shipping the
M1 Version!  Still the app works really well on this machine or on my much
older

 Great piece of software and a really responsive developer.

**Comment by joshstrange** [comment]
I just wanted to leave a comment for anyone like me that finds this issue and is worried about conversion time. On my M1 Max (maxed out RAM/GPU, though I don't think this matters a ton) the conversion process takes literally 2-3 seconds (I am running the M1 version of the app). 

I'm coming from a program called InAudible (you can find it on some closed forums) and was hesitant to pay for this because every other "DRM removing" or "Audible to MP3/M4B" program uses the "burn audiobook to virtual CD then rip it back"-process to remove the DRM and it takes a LONG time. Open Audible doesn't have any of these issues.

You won't regret paying for this software, I have hundreds of audiobooks in Audible and the thought of downloading them all alone from the web would be worth the $20 but saving the step of opening each book in InAudible and converting them is a godsend. This software combines both those steps and does it automatically for me, then all I have to do is grab the m4b's and throw them in Plex so I can use them with the Prologue audiobook app.

THANK YOU!
