### ISSUE TITLE
Looking for beta testers

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#839]
Looking for testers for the next release of OpenAudible:

https://openaudible.org/beta 

We recently added a build for the new Apple processors, called Apple Silicon or m1. Initial tests show a big improvement in speed. (4x and up.)  This adds a new java VM, newly built ffmpeg/ffprobe, and GUI widget library (eclipse swt.) So a lot of parts changed.

Got one report #831 that ffprobe was not working. 

We also made some changes for retina (high DPI) displays.. including a lot of new icons, a new installer DMG, and translations!

Please let me know if you see anything. We do have an outstanding issue with webkit on linux machines where the browser quits on logging in to audible... it is a pain, but we are working on a couple of solutions. If you want, you can copy your credentials.json from a pc or mac to your linux install to get around the problem. 

Thanks in advance for any feedback.

**Comment by chrisdlees** [comment]
Is this mainly a feature release for the new Apple Silicon? 
Are there any major changes to the linux or windows binaries?

**Comment by openaudible** [comment]
This will be 3.4 when released. 

Lots of changes but want to get more apple testers since that uses a lot of new code. 

for windows we switched the browser from IE to edge. New icons, better dark mode, high dpi support, image editing fix, export fix.

**Comment by openaudible** [comment]
Got a new beta 7 for apple silicon users posted. Report of success or failure appreciated.

**Comment by openaudible** [comment]
Thanks @oboe45   just waiting on new translations and apple silicon success reports.

**Comment by shelaffs** [comment]
I'm using the M1 3.3.0.7 beta at your recommendation. Macbook Air OSX 12.0.1 Monterey. 

Hard to gauge conversion speed since I downloaded and converted over 350 audibooks before discovering the beta, which took several days. Since using the beta I've downloaded about 10 more book and it does go by very quickly! So no useful feedback there, but no complaints either.  

I can report a couple of issues I've run into since using the beta, however: 
1. One audiobook (new purchase) will not download. Open Audible reads it as an aaxc file, but if I manually download from the Audible site I can get an aax file. 
3. I've also noticed the images for the cover art are dim - almost like they're displaying at a lowered opacity (like 70-80%). I use dark mode but the issue persists in light mode as well. 

Below screenshot shows both the dim image and the book I am having issues with. Thanks for your help!
<img width="1013" alt="Screen Shot 2022-01-27 at 5 29 29 PM" src="https://user-images.githubusercontent.com/44376090/151454369-8d1d9f64-778f-44ca-b7ab-137d8e934f0f.png">

Can confirm that once I revered to the 3.3 public release, both of these issues are no longer present so seems to be an issue in the beta release. 

<img width="1012" alt="Screen Shot 2022-01-27 at 5 33 33 PM" src="https://user-images.githubusercontent.com/44376090/151454657-8fb829c7-27be-4cf4-b5a1-a428ede6bed1.png">

**Comment by openaudible** [comment]
The image problem was a great catch. Only affected some macs. Fixed for final release. Thanks for the screenshots.

The AAXC thing might be a book that was purchased, and has since become free or part of a Romance collection... so that might be a tricky one. Might be able to figure out a way around it.

**Comment by openaudible** [comment]
Thanks everyone. Posting 3.4 today.
