### ISSUE TITLE
Organization Best Practices after convert?

### ISSUE THREAD

**Issue by tspinoso** [openaudible/openaudible#84]
Hi,  Thank you for the software very effective. 

After Mp3 convert I am left with something like BK_SANS_000222 or the like.    If I  go to properties of the file in windows explorer I can see the correct metadata with author, title, etc.... 

Should I manually organize by Author/Series/Title?  I assume you simply have to manually do this or can the software do it for me?  I wish there was something like Calibre for Audio books.

Any advice on how you manage these files for later consumption and organization would be appreciated.

**Comment by mikecook** [comment]
As a user who tracks audiobooks (and ebooks) within Calibre:

While the Audible books I own are all single file, the mp3 CD and CD ripped to FLAC audiobooks I own are usually multiple files per audiobook. Since Calibre can only manage single files per format, I zip all my audiobooks, then rename the .zip to .zab (zab is an audiobook format, but it is not just a renamed zip, this is definitely a misuse of the extension). If you don't like .zab, you can choose any extension that isn't already a format known to Calibre.

Calibre doesn't recognize .zab as a known format, but it will allow you to add arbitrary files and will track them assuming their extension is their format. To add these zab files, when Calibre gives you the 'Add Book' file selection dialog, you need to switch the default file type in the lower right hand of the dialog from 'Books' to 'All files' for the zabs to be visible.

zabs will show up in Calibre just like any format (including being listed/sortable in the Formats category), tracked with the same book as the epub and mobi formats, but don't expect apps like Calibre Companion to recognize or sync zabs (yet). 

When I click on zabs within Calibre, it opens them in my archive manager. I did not install the "open with" plugin.

I based my setup on this forum post:
https://www.mobileread.com/forums/showthread.php?t=234018

**Comment by tspinoso** [comment]
Thanks to both of you for the help - the export tip save me a great deal of time.

**Comment by tspinoso** [comment]
> If you Export Web Page from the File menu, all MP3's are renamed with the proper name.
> 

It looks likes this duplicates the files as well?

**Comment by openaudible** [comment]
It does duplicate the files. A bit of a waste.. but hard drives are cheap. I am contemplating a new file naming strategy, but don't want to F it up and cause problems for existing users.
