### ISSUE TITLE
Edit Book Screen data - Title/Short Title swapped

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#866]
Ver 3.4.2 Mac
in the event books are imported rather than downloaded I notice the title and short title fields are sometimes reversed

title = The Well of Ascension
shirt title = The Well of Ascension: Mistborn, Book 2
and they don't get matched to a Product ID/ASIN

**Comment by openaudible** [comment]
Importing from an AAX? Or external mp3?

**Comment by feldegast** [comment]
from an AAX

**Comment by feldegast** [comment]
do you need to restart openaudible after importing an AAX to for it to be matched?

**Comment by openaudible** [comment]
The titles in the aax file is not always perfectly aligned to the data on the audible API. 
But I haven't found any aax files that don't have a product id and ASIN.
But it can be possible to import a file that doesn't have a pid/asin.

But the expected behavior is if you connect to audible, get your books, then import your aax files (drag and drop) they should be copied into your library without book duplicates.

No restart after importing is needed. The log window should more or less say what it was doing-- skipping a file, found an existing book, etc. 

So I think to get a better error report, I'd need to get a better description:
Have book abc in library with pid/aisn  with no aax
Have aax file associated with that book. Drag and drop onto OA.
Expected behavior is aax file added to book, actual behavior is....

Or whatever you're seeing

**Comment by feldegast** [comment]
the AAX files have a product id and ASIN when initially downloaded by OA,
then the OA DB/Data got corrupted so i imported the AAX files into OA fresh
(drag and drop) and it is at that point some no longer had ASINs but some
did
i then set the duplicates (from audible server) after doing a sync (by
manually matching the book name) to ignore to not re-download them

is there a way to manually say "this already downloaded AAX is a match for
this other record from the server"?
by eg selecting both records (downloaded and not yet downloaded and then
manually matching/combining them?

"Have book abc in library with pid/aisn with no aax" i have the opposite to
this, drag and dropped AAX and it shows up "with no product id or ASIN"

**Comment by openaudible** [comment]
Confirmed. Good catch. Importing AAX files is not grabbing the product ID and asin.. Which is not shown using regular old ffprobe, but needs an additional more time-consuming parse aax. Will fix.

**Comment by feldegast** [comment]
it was the fact that the long and short names were swapped was my initial thought something was wrong, as I don't know what is or is not happening or supposed to happen in code but the long and short names being swapped just looked wrong
and the missing Product ID/ASIN I just was not sure how to get them to match online data

**Comment by openaudible** [comment]
Fixed for future versions.. although short title and long title may be slightly from imported aax files.. but should be better.

if you have aax files without ID's, you'll need to delete and re-import them. 
https://openaudible.org/beta
