### ISSUE TITLE
testing fix to issue #866 - book is in AAX directory but list doesn't show re-imported book

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#869]
tried in 3.4.3.1 beta
importing an AAX that was missing IDs, copied the AAX file elsewhere, deleted the book record from OA then tried to drag and drop AAX file
the AAX copy file dialog is displayed during import and the imported AAX file is in the AAX directory of OA but the list of books is not updated to show imported books....
doing a full library sync should find unmatched books so doing a full sync twice should have fewer found books the second time, but the sync has the same number of unmatched books both times.....

**Comment by openaudible** [comment]
Got the report.

According to the log file, it looks like you dropped an aax onto OA... and that book was already in the library, perhaps without the aax file, so that book was updated to now have the aax associated with it. (book ends with Duke and I) That should be expected behavior. 

Now the only thing I'm worried about is if you have an aax file book without asin/pid, and you also have the same book with asin/pid (with or without aax.) We don't currently have a good way to merge the two books into one book. Could get messy, especially if there are mp3's or m4b's associated with either books.

**Comment by feldegast** [comment]
it wasn't in the library, I deleted the library record before re-importing it
I see the AAX file in the AAX directory after the import but not listed in the library in the OA GUI

**Comment by feldegast** [comment]
as for merging records, either keep them separate or allow manual merging when the amazon IDs etc match or auto-match when the IDs are the same??

**Comment by feldegast** [comment]
found it....the book ending with 'Duke and I'
the dropped book went into Ignored for some reason even though it was not previously ignored

**Comment by openaudible** [comment]
Ok. That’s what the log was saying. Ignore book is an unusual feature. But we only ignore books manually. Maybe you were doing some testing. 😀

**Comment by feldegast** [comment]
i have some books that are only on the US server and some only on the AU server so I have to ignore duplicates but I don't think that one was in the ignore list when I re-imported it....
