### ISSUE TITLE
Download process fails to rename file

### ISSUE THREAD

**Issue by plmcgrn** [openaudible/openaudible#90]
I'm running on Mac, and I'm finding that the app generally works, but, it seems to have issues renaming  the AAX file after completing the download.  If I manually rename it and move it to the AAX folder, it has no problem converting to MP3.

In looking at the log file, I see it's a Java exception, but I don't see a way to get more detail on "why".

`<record>
  <date>2019-02-03T21:32:32</date>
  <millis>1549247552911</millis>
  <sequence>59</sequence>
  <logger>org.openaudible.util.queues.ThreadedQueue</logger>
  <level>INFO</level>
  <class>org.openaudible.util.queues.ThreadedQueue</class>
  <method>jobError</method>
  <thread>39</thread>
  <message>DownloadQueue error processing Download The Legend of Sleepy Hollow</message>
  <exception>
    <message>java.io.IOException: failed to rename./Users/paul/Library/OpenAudible/tmp/asin_B00N0ETQO4.AAX.part to /Users/paul/Library/OpenAudible/aax/asin_B00N0ETQO4.AAX</message>
    <frame>
      <class>org.openaudible.download.DownloadJob</class>
      <method>download</method>
      <line>259</line>
    </frame>
    <frame>
      <class>org.openaudible.download.DownloadJob</class>
      <method>downloadNew</method>
      <line>312</line>
    </frame>
    <frame>
      <class>org.openaudible.download.DownloadJob</class>
      <method>processJob</method>
      <line>327</line>
    </frame>
    <frame>
      <class>org.openaudible.util.queues.ThreadedQueue$JobThread</class>
      <method>run</method>
      <line>281</line>
    </frame>
  </exception>
</record>
 `

**Comment by openaudible** [comment]
Strange. The java call to rename the file (File.rename) only returns true or false, so we don't get a decent reason why. Usually the file is open, the destination is in use, you're low on disk space.. I'll change it to a renameOrCopy next version which should probably fix it. You could try from the command line:
mv /Users/paul/Library/OpenAudible/tmp/asin_B00N0ETQO4.AAX.part /Users/paul/Library/OpenAudible/aax/asin_B00N0ETQO4.AAX
and see if a better error message comes up.

**Comment by openaudible** [comment]
Kind of figured you might have a sym link to a smb but should still work. 

I switched to java 7+ Files.move which has better error reporting and it looks like it does a copy if it fails. 
But I may need to fall-back to a copy and then delete.. Let me know if it happens in 1.4.3.

**Comment by aljex** [comment]
I get the same problem, but I think it's because it's trying to rename a file across different filesystems.
I used the preferences to set both the Working and the Web/MP3 directories to a directory on an external drive.

But it's using my regular home dir for the downloads, which is non-intuitive given the preferences dialog.

WARNING: error downloading Galaxy's Edge, Part II: failed to rename./home/bkw/OpenAudible/tmp/BK_PODM_001191.AAX.part to /media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible/aax/BK_PODM_001191.AAX

I don't know why it says "./home" instead of "/home". That's an important distinction.

But, setting that aside for now, "/home/bkw" is on a different filesystem than "/media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d", and depending on the exact function/language/etc being used, you may not be able to move from the one name to the other in a single operation.

I've seen the same problem before in other apps. For instance a pandora client used to use C rename() from a tmp path to a final path, which only works within a filesystem, so it broke when /tmp was a tmpfs in ram for example.

Just for completeness: Permissions look ok for both source and destination paths:

User "bkw" has permission to delete files from the source "tmp" dir:
bkw@negre:~$ ls -l /home/bkw/OpenAudible
total 876
-rw-rw-r-- 1 bkw bkw 878130 Feb 20 20:56 books.json
-rw-rw-r-- 1 bkw bkw    164 Feb 20 17:45 directories.json
-rw-rw-r-- 1 bkw bkw    214 Feb  4 11:18 ignore.json
-rw-rw-r-- 1 bkw bkw     55 Jan 17 04:00 keys.json
-rw-rw-r-- 1 bkw bkw    223 Feb 20 15:35 settings.json
drwxrwxr-x 2 bkw bkw    140 Feb 20 20:53 tmp
bkw@negre:~$ 


User "bkw" has permission to create files in the destination "aax" directory:
bkw@negre:~$ ls -l /media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible
total 980
drwxrwxr-x 2 bkw bkw  20480 Jan 29 11:51 aax
drwxrwxr-x 2 bkw bkw  20480 Feb 20 19:57 art
-rw-rw-r-- 1 bkw bkw 874400 Feb  4 11:52 books.json
-rw-rw-r-- 1 bkw bkw    122 Feb  4 11:38 directories.json
-rw-rw-r-- 1 bkw bkw    214 Feb  4 11:18 ignore.json
-rw-rw-r-- 1 bkw bkw     55 Jan 17 04:00 keys.json
drwxrwxr-x 2 bkw bkw  20480 Feb  4 11:16 mp3
-rw-rw-r-- 1 bkw bkw    223 Feb  4 11:36 settings.json
drwxrwxr-x 2 bkw bkw    119 Feb  4 11:52 tmp
drwxrwxr-x 6 bkw bkw    109 Feb  3 02:01 web
bkw@negre:~$ 

The destination file does not already exist:
bkw@negre:~$ sudo ls -l /media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible/aax/BK_PODM_001191.AAX[sudo] password for bkw: 
ls: cannot access '/media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible/aax/BK_PODM_001191.AAX': No such file or directory
bkw@negre:~$ 

The destination filesystem is not mounted read-only by chance:
bkw@negre:~$ mount |grep media
/dev/sda1 on /media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d type xfs (rw,nosuid,nodev,relatime,attr2,inode64,noquota,uhelper=udisks2)
bkw@negre:~$ 

Further clue: it worked fine before I moved the directories all to the external drive.

But I can't go back to that way because:
bkw@negre:~$ du -sh /media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible
439G    /media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible

The base working directory ${HOME}/OpenAudible" does not seem to be configureable.
I'm not sure what the configurable paths are good for if you can't use them to do exactly this.

I think it needs 2 things:
1) The move/rename can't assume both source and dest are on the same filesystem. Use a function that allows for that, or do it in multiple copy-then-erase steps.
2) The browser should be downloading the .part files under the configured "Web" path.

#1 should resolve the error and make it work all by itself. (assuming this is actually the problem) #2 just makes the program actually do what it says on the tin, which might actually matter to someone.

**Comment by aljex** [comment]
I have a work-around for the download *.part vs final location being on different filesystems.
This is for linux, Lubuntu in my case. There are two main components to the work-around:
1) Use -Duser.home to force OpenAudible to work out of an arbitrary path instead of your real home dir.
2) A combination of a small launcher/wrapper script and a customized .desktop file to actually DO that for you with the least amount of hard coding.

* Exit OpenAudible if it's running

* Move the entire ~/OpenAudible directory wherever you want all the data and the tmp/*.part download dir to live. In my case, I already had most things moved because I had previously used the Preferences screen to set those two paths, and so it was only the *.json files and the tmp dir I still needed to move. In the end, leave no OpenAudible directory in your home dir.

* Create this launcher.sh file in the new OpenAudible directory wherever it is.
<pre>
#!/bin/bash
# launcher.sh - Launches OpenAudible with user.home set to the parent
# of whatever directory launcher.sh is in.
#
# Brian K. White b.kenyon.w@gmail.com

x="${0%/*}"
x="${x%/*}"
export _JAVA_OPTIONS=-Duser.home="${x}"
/opt/OpenAudible/OpenAudible
</pre>

* chmod 755 launcher.sh

* Move /usr/share/applications/OpenAudible.desktop to ~/.local/applications
It needs to be customized with a path inside that would be wrong in the global/shared one in /usr/share, and yet you don't want 2 copies to appear in your desktop menus, so just move the global one to your users own applications directory, and copy it again for any other users. There is still a generic global reference one in /opt/OpenAudible if you're worried about losing the reference. This part is not ideal because any time you update the app, the .deb will install a new /usr/share/applications/OpenAudible.desktop So this needs a better answer long term, but for now it makes the app work at least.

* Delete directories.json
This is to ensure that when the app starts up again the first time after the move, it does NOT remember or try to use any of the old paths where it used to live.

* Edit ~/.local/applications/OpenAudible.desktop to look like this:
Obviously make "Exec=" the path to your /path/to/OpenAudible/launcher.sh wherever that is.
It's ok that this path doesn't actually exist except when the external drive is plugged in or when the share on your home has is mounted etc. That's actually a good thing so you don't accidentally run OpenAudible except when it's data is actually present.
<pre>
[Desktop Entry]
Type=Application
Name=OpenAudible
Exec=/media/bkw/054cc493-8a17-4cec-bb7e-09b9a64a3b8d/bkw/OpenAudible/launcher.sh
Icon=/opt/OpenAudible/.install4j/OpenAudible.png
Categories=Audio;Player;Java;Literature;Database
</pre>

Now look in your desktop menus in whatever sub-menu the other audio/video apps mostly appear in. In my case in LXQT there is a menu called "Sound & Video", and OpenAudible appears in there now, instead of "Other" where it used to appear. This is because of the Categories=... line.

The app should launch, and NOT create any OpenAudible directory in your real home dir any more. OpenAudible now thinks your home dir is the parent dir of wherever launcher.sh is.

So in my case, launcher.sh is /media/bkw/uuid_of_a_usb-c_ssd/bkw/OpenAudible/launcher.sh
When I run launcher.sh, it figures out what it's own name is ($0), 2 path elements from the end of that, and sets an environment variable that affects java to override the user.home property equal to "/media/bkw/uuid_of_a_usb-c_ssd/bkw" . The env variable would affect any/all java apps, so we don't do it in your .profile, just in a wrapper script so the only thing it affects is that script.

You can now copy the whole OpenAudible directory anywhere, including all your downloaded aax, converted mp3, and your library database and app settings in the json files, and the launcher.sh.

You can also just run launcher.sh manually, not from a .desktop file, but the dir on the external drive witll not be in your $PATH.

Now my OpenAudible is fully functional and running from an arbitrary directory on an external like a fully portable app. Downloads are working and convert to mp3 are working. Downloads are writing the partial download temp files in /media/.../OpenAudible/tmp/*.part , and successfully renaming saving the final file by renaming from /media/.../tmp/*.part to /media/.../aax/*.aax, and then successfully converting to mp3 after that.

Since my OpenAudible is now working when it wasn't before, this proves that the problem was indeed simply the fact that the app is trying to use a simple rename function similar to the C rename() (I don't know what the java equivalent is), which only works within a filesystem. So, until that unsafe assumption is fixed, user.home and the "Web/MP3" setting cannot be on different filesystems.

When you want to move the OpenAudible dir to a new drive or path, you need to do 2 things before trying to launch the app again:
* Edit the path to launcher.sh in OpenAudible.desktop
* Delete directories.json

The app icon will be in your desktop start menu all the time, whether the external drive or network share is connected or not, but clicking the icon simply won't do anything except when the drive is actually connected. It's harmless to try to run it even when the drive is not connected.

This can actually be made even more portable and automatic with a little more scripting, although I assume OpenAudible will probably simply improve the app itself to make this unnecessary sooner or later, since the changes needed inside the app should not be major. This is just a work-around for now.

**Comment by openaudible** [comment]
I have updated my software to use a smarter rename.. I will post a beta (or new version?) shortly. Thanks for posting the work-around. In the process of using the book title for file names.. Taking longer than I thought.. and today my hosting account got suspended.

**Comment by openaudible** [comment]
Hey, I posted a new version 1.4.3 with the new rename code. Please let me know if that fixes your issue... if not, please open a new Ticket with a reference to this one #90.
