### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by cat24max** [openaudible/openaudible#91]
All my books have the download buttons greyed out and task says: "Unable to download".
Nothing helpful in the console.

Did Audible break something?

**Comment by cat24max** [comment]
Region: DE
I just submitted a bug report.
And yes, the files definitely haven't been downloaded.
There is the Download button, but it just redirects you to an ad for their Cloud Player and other apps.

I downloaded OpenAudible on Mac yesterday and it worked without an issue, downloading and converting my books.
I have no idea why it doesn't work on Windows.

**Comment by Bhlowe** [comment]
Its possible we're not alerting you that you need to make a setting change, since we don't have any test accounts in DE. 

I saw your bug report, but it didn't include any unparsed .html files, which are erased every time you restart the app. If you want to send a better report, start the app, reproduce the problem (load your library), and send a bug report with the Issue 91 tag.



From the Documentation: 

Audible has a setting you need to change if you have problems downloading books.

If you see a message about How To Listen or an alert about the need to change a setting, follow these instructions.  (YOU MAY NOT BE SEEING THIS MESSAGE because we are looking for a link to a page called "how to listen", which is probably translated into German.)

Go to audible settings. 

https://openaudible.org/settings.html

Ensure the Check for Audible Download Manager setting is unchecked, try downloading a file again.

**Comment by openaudible** [comment]
See:
https://openaudible.org/settings.html

**Comment by cat24max** [comment]
Yes, that's it. Didn't read that while searching for the error.
Maybe add "If everything is greyed out, do this". Because on my Mac it worked without changig the setting.
