### ISSUE TITLE
Question: What are the files in the folder ZxcvbnData?

### ISSUE THREAD

**Issue by dang1507** [openaudible/openaudible#958]
I found this folder here /users/<username>/AppData/Local/OpenAudible/EBWebView/ZxcvbnData

There is a passwords.txt file in this directory. What is the purpose of this file?

Thanks

**Comment by openaudible** [comment]
That is news to me... but it turns out it is a known thing. We use an internal web browser to log in and to display simple html.

It looks like that folder was created by webview, which is the Edge browser that is used for Windows. 

It can be safely removed.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2023
which links to here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32


Thanks for the heads up.
