### ISSUE TITLE
FEATURE REQUEST:  More options for the sort pane

### ISSUE THREAD

**Issue by qwksilver** [openaudible/openaudible#995]
![image](https://user-images.githubusercontent.com/20508309/183555660-230de89e-f4a9-4bbd-a126-9f372c9d191d.png)

It would be nice to add things to this listing publish, isbn, and account tied to would be nice.

**Comment by openaudible** [comment]
You mean publisher? The account isn't currently saved with the book.. and the ASIN is pretty random number that isn't too useful. Marking as a feature request to allow ability to add and move columns.. but we typically recommend using a web browser to browse your audible library.

**Comment by qwksilver** [comment]
I did mean publish, and i actualy want the isbn data when it exists, and what account i have the book in.  I have seen multiple requests for better account management, i personally have access to many, mine, wifes, kids, legacy account from a friend that passed, etc.  and if i want to see if i have a book somewhere it's also nice to know where to go to get it if i do.  so this is a FR to expand the data available a bit, and make the columns in the desktop app more configurable i suppose.

**Comment by openaudible** [comment]
Marked as feature request. Trying to keep things simple but understand your request.

**Comment by qwksilver** [comment]
I'm curious about the work flow here.  usually closed implies that it's finished and now a part of the program, but i have seen many items "closed" that are obviously not part of the program (mostly those related to multiple user simplification).  can you help me understand if the issue is on the to-do list somewhere else.  Because currently my idea just feels discarded...

**Comment by openaudible** [comment]
There is no todo list, but you can search for "feature request" in issues to see what is being requested.

We use the "issues" to flag important changes that need to be fixed before the next release or to answer questions that come up from users.  If a feature request is simple and can be added to the next release, we'll keep it open and close it when it has been added to a beta or production release. Otherwise, feature requests are closed after being acknowledged, regardless of priority or likelihood of them getting added. If and when features are added, we go back and say the feature has been added to version x.y.z.  

Obviously it would be impractical to implement every feature request. We have limited resources. 

Yes, we have a big backlog of requested features to implement. Mostly with regard to file naming structure, multiple accounts, audible plus, and web page integration. Those are the priorities. But we're also trying to keep the UI complexity to a minimum to keep the product simple and keep support minimal. 

Thanks for your interest and understanding.
